### PR TITLE
Display transported players in log for transporter

### PR DESCRIPTION
**Pull request by GuuscoNL**
Displays transported players in log for transporter. I am not sure if I did the names correctly, since I could not test the custom names my self. I just copied some code that was already there and I hope that does the job. Feel free to change the log message, since I wasn't sure what to put there. I hope this is usefull!

Here is a screenshot of how it looks in-game:
image

PS. This time I made sure the formatting is not terrible :)

### CODE REVIEW

**Comment by oninoni** [comment]
Did you test it?

**Comment by GuuscoNL** [comment]
#### Tests I have done:
**1.** Transporting my self (success)
**2.** Transporting my self with bots (success)
**3.** Transporting normal objects (success)
**4.** Transporting 7 bots (success)
**5.** Transporting bots and normal objects (success)

The only thing I am not sure about is if the names in the logs are correct (That it is showing "LT Guus" or "LT CMD Charles Fawcett" instead of there steam usernames). I don't know how to test this.

**Comment by GuuscoNL** [comment]
Possible alternative log messages:
1. Life Forms being transported: ...
2. Life Forms: ...
3. Life Forms in Patterns: ...

**Comment by GuuscoNL** [comment]
Last commit (f2e91347b6970eb42a191929a925d31724fd1647) : Log entry order changed so that the log entry with the player names comes before the dematerialising entry's. As well as showing the amount of life forms detected.

Now looks like this:
image

Passed all the previous tests I mentioned.

I do have a new idea: What if we show the name of the player that is being transported to the buffer instead of just an organic pattern? Of course if it's an NPC it will still be an organic pattern. What do you think? I can implement it if you think it's a good idea.

**Comment by oninoni** [comment]
Personally i would say, that the "Dematerialising Object" should be replaced instead dont you think?
We got a line per object anyways.
I was waiting to finish my sensor integration, to allow a good way of reading whatever information is important.

**Comment by GuuscoNL** [comment]
What it looks like now when transporting 5 bots and 1 barrel. As well as a new message when a lifeform is transported to the buffer:
image

(Many bots were harmed during testing)

**Pull request merged**
